import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "#A98467",
    borderRadius: 10,
    margin: 20,
    marginBottom: 0,
    padding: 16,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    position: "relative",
    paddingTop: 35,
    elevation: 10,
  },
  containerDosezki: {
    backgroundColor: "#A98467",
    borderRadius: 10,
    margin: 20,
    marginBottom: 0,
    paddingBottom: 10,
    position: "relative",
    elevation: 10,
  },
  username: {
    color: "#F0EAD2",
    fontSize: 15,
    letterSpacing: 0.3,
    fontWeight: "bold",
    alignSelf: "flex-start",
  },
  infoBox: {
    backgroundColor: "#6C584C",
    borderRadius: 10,
    padding: 16,
    display: "flex",
    flexDirection: "row",
    gap: 40,
    marginLeft: 70,
    alignItems: "flex-end",
    justifyContent: "flex-end",
    elevation: 10,
  },
  infoBoxValues: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    alignContent: "flex-end",
  },
  infoBoxLabels: {
    display: "flex",
    flexDirection: "column",
    gap: 15,
        alignItems: "flex-end",
      
  },
  levelIcon: {
    width: 70,
    height: 80,
  },
  value: {
    color: "#BC9143",
    fontSize: 18,
    fontWeight: "bold",
  },
  label: {
    color: "#F0EAD2",
    fontSize: 14,
    letterSpacing: 0.3,
    fontWeight: "bold",
  },
  odjavaButton: {
    position: "absolute",
    top: -12,
    right: 8,
    backgroundColor: "red",
    color: "#F0EAD2",
    letterSpacing: 0.3,
    fontSize: 16,
    fontWeight: "bold",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 10,
    elevation: 3,
  },
  logoutButton: {
    marginTop: 12,
    backgroundColor: "red",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  logoutText: {
    color: "#F0EAD2",
    fontWeight: "bold",
    letterSpacing: 0.4,
    fontSize: 16,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 4,
    gap: 50,
  },
  heading: {
    fontSize: 20,
    fontWeight: "bold",
    margin: 10,
    paddingHorizontal: 10,
    color: "#F0EAD2",
    letterSpacing: 0.3,
  },
  listContainer: {
    paddingHorizontal: 0,
  },
  card: {
    backgroundColor: "#6C584C",
    padding: 12,
    marginRight: 15,
    marginLeft: 15,
    marginBottom: 15,
    borderRadius: 8,
    width: 140,
    height: 120,
    alignItems: "center",
    elevation: 10,
  },
  cardTitle: {
    fontWeight: "bold",
    color: "#F0EAD2",
    fontSize: 11,
    marginBottom: -15,
  },
  achievementIcon: {
    width: 75,
    height: 75,
    resizeMode: "contain",
  },
  profileContentContainer: {
    flex: 1,
    backgroundColor: "#6C584C",
  },
  starsWrapper: {
    flexDirection: "row",
    gap: 2,
  },
  starIcon: {
    width: 23,
    height: 23,
  },
  noAchievementsText: {
    fontWeight: "bold",
    color: "#F0EAD2",
    fontSize: 16,
    alignSelf: "center",
    margin: 55,
  },
});
